version: "2"

services:

  dta:
    image: jungleran/drupal-base:8.5.3-apache
    container_name: dta
    volumes:
      - ./:/var/www/html
    ports:
      - 5000:80
    restart: always

  dtadb:
    image: mysql:5.7.21
    container_name: dtadb
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always

  dtadrush:
    image: jungleran/drush:8.5.3-apache
    container_name: dtadrush
    hostname: drush
    volumes_from:
      - dta
    entrypoint:
      - bash
    tty: true

  dtaadminer:
    image: adminer:4.6.2-standalone
    container_name: dtaadminer
    ports:
      - 5001:8080
