version: "2"

services:

  web:
    image: jungleran/drupal-base:8.5.2-apache
    container_name: web
    volumes:
      - ./:/var/www/html
    ports:
      - 5000:80
    restart: always

  db:
    image: mysql:5.7.21
    container_name: db
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always

  drush:
    image: jungleran/drush:8.5.2-apache
    container_name: drush
    hostname: drush
    volumes_from:
      - web
    entrypoint:
      - bash
    tty: true

  adminer:
    image: adminer:4.6.2-standalone
    container_name: adminer
    ports:
      - 5001:8080
